device_name = "AT Translated Set 2 keyboard"

[[dual_role]]
input = "KEY_CAPSLOCK"
hold = ["KEY_LEFTCTRL"]
tap = ["KEY_ESC"]

[[remap]]
input = ["KEY_ESC"]
output = ["KEY_CAPSLOCK"]

# Remap right alt + hjkl to arrow keys
[[remap]]
input = ["KEY_RIGHTALT", "KEY_H"]
output = ["KEY_LEFT"]

[[remap]]
input = ["KEY_RIGHTALT", "KEY_J"]
output = ["KEY_DOWN"]

[[remap]]
input = ["KEY_RIGHTALT", "KEY_K"]
output = ["KEY_UP"]

[[remap]]
input = ["KEY_RIGHTALT", "KEY_L"]
output = ["KEY_RIGHT"]

# Remap left ctrl + some hard to reach keys to more accessible keys
[[remap]]
input = ["KEY_LEFTALT", "KEY_Q"]
output = ["KEY_LEFTCTRL", "KEY_Q"]

[[remap]]
input = ["KEY_LEFTALT", "KEY_W"]
output = ["KEY_LEFTCTRL", "KEY_W"]

[[remap]]
input = ["KEY_LEFTALT", "KEY_E"]
output = ["KEY_LEFTCTRL", "KEY_E"]

[[remap]]
input = ["KEY_LEFTALT", "KEY_A"]
output = ["KEY_LEFTCTRL", "KEY_A"]

[[remap]]
input = ["KEY_LEFTALT", "KEY_S"]
output = ["KEY_LEFTCTRL", "KEY_S"]

[[remap]]
input = ["KEY_LEFTALT", "KEY_Z"]
output = ["KEY_LEFTCTRL", "KEY_Z"]

[[remap]]
input = ["KEY_LEFTALT", "KEY_X"]
output = ["KEY_LEFTCTRL", "KEY_X"]

[[remap]]
input = ["KEY_LEFTALT", "KEY_C"]
output = ["KEY_LEFTCTRL", "KEY_C"]

[[remap]]
input = ["KEY_LEFTALT", "KEY_V"]
output = ["KEY_LEFTCTRL", "KEY_V"]

[[remap]]
input = ["KEY_LEFTALT", "KEY_TAB"]
output = ["KEY_LEFTCTRL", "KEY_TAB"]

[[remap]]
input = ["KEY_LEFTALT", "KEY_GRAVE"]
output = ["KEY_LEFTCTRL", "KEY_GRAVE"]
