device_name = "AT Translated Set 2 keyboard"

[[dual_role]]
input = "KEY_CAPSLOCK"
hold = ["KEY_LEFTCTRL"]
tap = ["KEY_ESC"]

[[remap]]
input = ["KEY_ESC"]
output = ["KEY_CAPSLOCK"]

[[remap]]
input = ["KEY_RIGHTALT", "KEY_H"]
output = ["KEY_LEFT"]

[[remap]]
input = ["KEY_RIGHTALT", "KEY_J"]
output = ["KEY_DOWN"]

[[remap]]
input = ["KEY_RIGHTALT", "KEY_K"]
output = ["KEY_UP"]

[[remap]]
input = ["KEY_RIGHTALT", "KEY_L"]
output = ["KEY_RIGHT"]

[[remap]]
input = ["KEY_LEFTALT", "KEY_Q"]
output = ["KEY_LEFTCTRL", "KEY_Q"]

[[remap]]
input = ["KEY_LEFTALT", "KEY_W"]
output = ["KEY_LEFTCTRL", "KEY_W"]

[[remap]]
input = ["KEY_LEFTALT", "KEY_E"]
output = ["KEY_LEFTCTRL", "KEY_E"]

[[remap]]
input = ["KEY_LEFTALT", "KEY_R"]
output = ["KEY_LEFTCTRL", "KEY_R"]

[[remap]]
input = ["KEY_LEFTALT", "KEY_T"]
output = ["KEY_LEFTCTRL", "KEY_T"]

[[remap]]
input = ["KEY_LEFTALT", "KEY_A"]
output = ["KEY_LEFTCTRL", "KEY_A"]

[[remap]]
input = ["KEY_LEFTALT", "KEY_S"]
output = ["KEY_LEFTCTRL", "KEY_S"]

[[remap]]
input = ["KEY_LEFTALT", "KEY_D"]
output = ["KEY_LEFTCTRL", "KEY_D"]

[[remap]]
input = ["KEY_LEFTALT", "KEY_F"]
output = ["KEY_LEFTCTRL", "KEY_F"]

[[remap]]
input = ["KEY_LEFTALT", "KEY_Z"]
output = ["KEY_LEFTCTRL", "KEY_Z"]

[[remap]]
input = ["KEY_LEFTALT", "KEY_X"]
output = ["KEY_LEFTCTRL", "KEY_X"]

[[remap]]
input = ["KEY_LEFTALT", "KEY_C"]
output = ["KEY_LEFTCTRL", "KEY_C"]

[[remap]]
input = ["KEY_LEFTALT", "KEY_V"]
output = ["KEY_LEFTCTRL", "KEY_V"]

[[remap]]
input = ["KEY_LEFTALT", "KEY_W"]
output = ["KEY_LEFTCTRL", "KEY_W"]
